/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheelleg_nmpc_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s6[19] = {7, 7, 0, 1, 2, 4, 6, 7, 8, 9, 0, 1, 2, 3, 2, 3, 4, 5, 6};
static const casadi_int casadi_s7[3] = {0, 0, 0};
static const casadi_int casadi_s8[10] = {0, 7, 0, 0, 0, 0, 0, 0, 0, 0};

/* wheelleg_nmpc_cost_ext_cost_fun_jac_hess:(i0[5],i1[2],i2[0],i3[9])->(o0,o1[7],o2[7x7,9nz],o3[],o4[0x7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3]? arg[3][8] : 0;
  a1=10.;
  a2=arg[0]? arg[0][0] : 0;
  a3=arg[3]? arg[3][0] : 0;
  a2=(a2-a3);
  a3=(a1*a2);
  a4=(a3*a2);
  a5=arg[0]? arg[0][1] : 0;
  a6=arg[3]? arg[3][1] : 0;
  a5=(a5-a6);
  a6=(a1*a5);
  a7=(a6*a5);
  a4=(a4+a7);
  a7=5.;
  a8=arg[0]? arg[0][2] : 0;
  a9=arg[3]? arg[3][2] : 0;
  a8=(a8-a9);
  a10=sin(a8);
  a8=cos(a8);
  a11=atan2(a10,a8);
  a12=(a7*a11);
  a13=(a12*a11);
  a4=(a4+a13);
  a13=arg[0]? arg[0][3] : 0;
  a14=arg[3]? arg[3][3] : 0;
  a13=(a13-a14);
  a14=casadi_sq(a13);
  a4=(a4+a14);
  a14=arg[0]? arg[0][4] : 0;
  a15=arg[3]? arg[3][4] : 0;
  a14=(a14-a15);
  a15=casadi_sq(a14);
  a4=(a4+a15);
  a15=20.;
  a16=0.;
  a17=5.0000000000000000e-01;
  a18=arg[3]? arg[3][7] : 0;
  a17=(a17-a18);
  a16=casadi_fmax(a16,a17);
  a16=casadi_sq(a16);
  a15=(a15*a16);
  a4=(a4+a15);
  a15=50.;
  a16=cos(a9);
  a17=(a16*a5);
  a9=sin(a9);
  a18=(a9*a2);
  a17=(a17-a18);
  a18=casadi_sq(a17);
  a18=(a15*a18);
  a4=(a4+a18);
  a4=(a0*a4);
  a18=1.0000000000000001e-01;
  a19=arg[1]? arg[1][0] : 0;
  a20=arg[3]? arg[3][5] : 0;
  a19=(a19-a20);
  a20=(a18*a19);
  a19=(a20*a19);
  a21=arg[1]? arg[1][1] : 0;
  a22=arg[3]? arg[3][6] : 0;
  a21=(a21-a22);
  a18=(a18*a21);
  a21=(a18*a21);
  a19=(a19+a21);
  a4=(a4+a19);
  if (res[0]!=0) res[0][0]=a4;
  a20=(a20+a20);
  if (res[1]!=0) res[1][0]=a20;
  a18=(a18+a18);
  if (res[1]!=0) res[1][1]=a18;
  a3=(a3*a0);
  a2=(a2*a0);
  a2=(a1*a2);
  a3=(a3+a2);
  a17=(a17+a17);
  a15=(a15*a0);
  a17=(a17*a15);
  a2=(a9*a17);
  a3=(a3-a2);
  if (res[1]!=0) res[1][2]=a3;
  a17=(a16*a17);
  a6=(a6*a0);
  a5=(a5*a0);
  a5=(a1*a5);
  a6=(a6+a5);
  a17=(a17+a6);
  if (res[1]!=0) res[1][3]=a17;
  a12=(a12*a0);
  a11=(a11*a0);
  a11=(a7*a11);
  a12=(a12+a11);
  a11=(a10*a12);
  a17=(a10*a11);
  a6=(a8*a12);
  a5=(a8*a6);
  a17=(a17+a5);
  if (res[1]!=0) res[1][4]=a17;
  a13=(a13+a13);
  a13=(a13*a0);
  if (res[1]!=0) res[1][5]=a13;
  a14=(a14+a14);
  a14=(a14*a0);
  if (res[1]!=0) res[1][6]=a14;
  a14=2.0000000000000001e-01;
  if (res[2]!=0) res[2][0]=a14;
  if (res[2]!=0) res[2][1]=a14;
  a1=(a1*a0);
  a1=(a1+a1);
  a14=(a9+a9);
  a14=(a15*a14);
  a14=(a9*a14);
  a14=(a1+a14);
  if (res[2]!=0) res[2][2]=a14;
  a14=(a16+a16);
  a15=(a15*a14);
  a9=(a9*a15);
  a9=(-a9);
  if (res[2]!=0) res[2][3]=a9;
  if (res[2]!=0) res[2][4]=a9;
  a16=(a16*a15);
  a16=(a16+a1);
  if (res[2]!=0) res[2][5]=a16;
  a11=(a11*a8);
  a16=(a12*a8);
  a7=(a7*a0);
  a7=(a7+a7);
  a1=(a10*a7);
  a16=(a16+a1);
  a16=(a10*a16);
  a11=(a11+a16);
  a7=(a8*a7);
  a12=(a12*a10);
  a7=(a7-a12);
  a8=(a8*a7);
  a6=(a6*a10);
  a8=(a8-a6);
  a11=(a11+a8);
  if (res[2]!=0) res[2][6]=a11;
  a11=2.;
  a11=(a11*a0);
  if (res[2]!=0) res[2][7]=a11;
  if (res[2]!=0) res[2][8]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheelleg_nmpc_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int wheelleg_nmpc_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real wheelleg_nmpc_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheelleg_nmpc_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheelleg_nmpc_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheelleg_nmpc_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheelleg_nmpc_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
