/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[4] = {0, 1, 0, 0};
static const casadi_int casadi_s2[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[17] = {7, 7, 0, 2, 4, 5, 6, 7, 7, 7, 0, 1, 0, 1, 2, 3, 4};
static const casadi_int casadi_s5[3] = {0, 0, 0};
static const casadi_int casadi_s6[10] = {0, 7, 0, 0, 0, 0, 0, 0, 0, 0};

/* wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess:(i0[7],i1[0],i2[0],i3[24])->(o0,o1[7],o2[7x7,7nz],o3[],o4[0x7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3]? arg[3][12] : 0;
  a1=arg[3]? arg[3][13] : 0;
  a2=arg[0]? arg[0][0] : 0;
  a3=arg[3]? arg[3][0] : 0;
  a3=(a2-a3);
  a4=casadi_sq(a3);
  a5=arg[0]? arg[0][1] : 0;
  a6=arg[3]? arg[3][1] : 0;
  a6=(a5-a6);
  a7=casadi_sq(a6);
  a4=(a4+a7);
  a4=(a1*a4);
  a7=arg[3]? arg[3][14] : 0;
  a8=arg[0]? arg[0][2] : 0;
  a9=arg[3]? arg[3][2] : 0;
  a8=(a8-a9);
  a10=casadi_sq(a8);
  a10=(a7*a10);
  a4=(a4+a10);
  a10=arg[3]? arg[3][15] : 0;
  a11=arg[0]? arg[0][3] : 0;
  a12=arg[3]? arg[3][3] : 0;
  a11=(a11-a12);
  a12=casadi_sq(a11);
  a12=(a10*a12);
  a4=(a4+a12);
  a12=arg[3]? arg[3][23] : 0;
  a13=arg[0]? arg[0][4] : 0;
  a14=arg[3]? arg[3][4] : 0;
  a13=(a13-a14);
  a14=casadi_sq(a13);
  a14=(a12*a14);
  a4=(a4+a14);
  a14=arg[3]? arg[3][18] : 0;
  a15=0.;
  a16=arg[3]? arg[3][19] : 0;
  a17=arg[3]? arg[3][7] : 0;
  a18=arg[3]? arg[3][10] : 0;
  a19=arg[3]? arg[3][8] : 0;
  a2=(a2-a19);
  a2=(a18*a2);
  a17=(a17+a2);
  a2=arg[3]? arg[3][11] : 0;
  a19=arg[3]? arg[3][9] : 0;
  a5=(a5-a19);
  a5=(a2*a5);
  a17=(a17+a5);
  a16=(a16-a17);
  a17=casadi_fmax(a15,a16);
  a5=casadi_sq(a17);
  a5=(a14*a5);
  a4=(a4+a5);
  a5=arg[3]? arg[3][20] : 0;
  a19=cos(a9);
  a20=(a19*a6);
  a9=sin(a9);
  a21=(a9*a3);
  a20=(a20-a21);
  a21=casadi_sq(a20);
  a21=(a5*a21);
  a4=(a4+a21);
  a4=(a0*a4);
  if (res[0]!=0) res[0][0]=a4;
  a3=(a3+a3);
  a1=(a1*a0);
  a3=(a3*a1);
  a20=(a20+a20);
  a5=(a5*a0);
  a20=(a20*a5);
  a4=(a9*a20);
  a21=(a15<=a16);
  a16=(a16<=a15);
  a16=(a16+a21);
  a21=(a21/a16);
  a17=(a17+a17);
  a14=(a14*a0);
  a17=(a17*a14);
  a17=(a21*a17);
  a16=(a18*a17);
  a4=(a4+a16);
  a3=(a3-a4);
  if (res[1]!=0) res[1][0]=a3;
  a20=(a19*a20);
  a17=(a2*a17);
  a20=(a20-a17);
  a6=(a6+a6);
  a6=(a6*a1);
  a20=(a20+a6);
  if (res[1]!=0) res[1][1]=a20;
  a8=(a8+a8);
  a7=(a7*a0);
  a8=(a8*a7);
  if (res[1]!=0) res[1][2]=a8;
  a11=(a11+a11);
  a10=(a10*a0);
  a11=(a11*a10);
  if (res[1]!=0) res[1][3]=a11;
  a13=(a13+a13);
  a12=(a12*a0);
  a13=(a13*a12);
  if (res[1]!=0) res[1][4]=a13;
  if (res[1]!=0) res[1][5]=a15;
  if (res[1]!=0) res[1][6]=a15;
  a15=2.;
  a1=(a15*a1);
  a13=(a9+a9);
  a13=(a5*a13);
  a13=(a9*a13);
  a0=(a21*a18);
  a0=(a0+a0);
  a0=(a14*a0);
  a0=(a21*a0);
  a0=(a18*a0);
  a13=(a13+a0);
  a13=(a1+a13);
  if (res[2]!=0) res[2][0]=a13;
  a13=(a19+a19);
  a5=(a5*a13);
  a9=(a9*a5);
  a13=(a21*a2);
  a13=(a13+a13);
  a14=(a14*a13);
  a21=(a21*a14);
  a18=(a18*a21);
  a9=(a9-a18);
  a9=(-a9);
  if (res[2]!=0) res[2][1]=a9;
  if (res[2]!=0) res[2][2]=a9;
  a19=(a19*a5);
  a2=(a2*a21);
  a19=(a19+a2);
  a19=(a19+a1);
  if (res[2]!=0) res[2][3]=a19;
  a7=(a15*a7);
  if (res[2]!=0) res[2][4]=a7;
  a10=(a15*a10);
  if (res[2]!=0) res[2][5]=a10;
  a15=(a15*a12);
  if (res[2]!=0) res[2][6]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
