/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheelleg_nmpc_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[19] = {7, 2, 0, 7, 14, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s5[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s6[49] = {45, 1, 0, 45, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44};

/* wheelleg_nmpc_expl_ode_hess:(i0[7],i1[7x7],i2[7x2],i3[7],i4[2],i5[19])->(o0[9],o1[45]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[3]? arg[3][1] : 0;
  a4=(a2*a3);
  a5=(a1*a4);
  a0=sin(a0);
  a6=arg[3]? arg[3][0] : 0;
  a2=(a2*a6);
  a7=(a0*a2);
  a5=(a5-a7);
  if (res[0]!=0) res[0][2]=a5;
  a5=(a0*a3);
  a7=arg[3]? arg[3][3] : 0;
  a8=arg[5]? arg[5][17] : 0;
  a9=5.0000000000000003e-02;
  a8=casadi_fmax(a8,a9);
  a7=(a7/a8);
  a5=(a5-a7);
  a8=(a1*a6);
  a5=(a5+a8);
  if (res[0]!=0) res[0][3]=a5;
  a5=arg[3]? arg[3][2] : 0;
  a8=arg[3]? arg[3][4] : 0;
  a10=arg[5]? arg[5][18] : 0;
  a10=casadi_fmax(a10,a9);
  a8=(a8/a10);
  a5=(a5-a8);
  if (res[0]!=0) res[0][4]=a5;
  if (res[0]!=0) res[0][5]=a7;
  if (res[0]!=0) res[0][6]=a8;
  a8=arg[3]? arg[3][5] : 0;
  if (res[0]!=0) res[0][7]=a8;
  a8=arg[3]? arg[3][6] : 0;
  if (res[0]!=0) res[0][8]=a8;
  a8=arg[1]? arg[1][2] : 0;
  a7=arg[1]? arg[1][3] : 0;
  a5=(a3*a7);
  a5=(a1*a5);
  a10=(a0*a8);
  a9=(a4*a10);
  a5=(a5-a9);
  a9=(a1*a8);
  a11=(a2*a9);
  a12=(a6*a7);
  a12=(a0*a12);
  a11=(a11+a12);
  a5=(a5-a11);
  a8=(a8*a5);
  a9=(a3*a9);
  a10=(a6*a10);
  a9=(a9-a10);
  a7=(a7*a9);
  a8=(a8+a7);
  if (res[1]!=0) res[1][0]=a8;
  a8=arg[1]? arg[1][9] : 0;
  a7=(a8*a5);
  a10=arg[1]? arg[1][10] : 0;
  a11=(a10*a9);
  a7=(a7+a11);
  if (res[1]!=0) res[1][1]=a7;
  a7=arg[1]? arg[1][16] : 0;
  a11=(a7*a5);
  a12=arg[1]? arg[1][17] : 0;
  a13=(a12*a9);
  a11=(a11+a13);
  if (res[1]!=0) res[1][2]=a11;
  a11=arg[1]? arg[1][23] : 0;
  a13=(a11*a5);
  a14=arg[1]? arg[1][24] : 0;
  a15=(a14*a9);
  a13=(a13+a15);
  if (res[1]!=0) res[1][3]=a13;
  a13=arg[1]? arg[1][30] : 0;
  a15=(a13*a5);
  a16=arg[1]? arg[1][31] : 0;
  a17=(a16*a9);
  a15=(a15+a17);
  if (res[1]!=0) res[1][4]=a15;
  a15=arg[1]? arg[1][37] : 0;
  a17=(a15*a5);
  a18=arg[1]? arg[1][38] : 0;
  a19=(a18*a9);
  a17=(a17+a19);
  if (res[1]!=0) res[1][5]=a17;
  a17=arg[1]? arg[1][44] : 0;
  a19=(a17*a5);
  a20=arg[1]? arg[1][45] : 0;
  a21=(a20*a9);
  a19=(a19+a21);
  if (res[1]!=0) res[1][6]=a19;
  a19=arg[2]? arg[2][2] : 0;
  a21=(a19*a5);
  a22=arg[2]? arg[2][3] : 0;
  a23=(a22*a9);
  a21=(a21+a23);
  if (res[1]!=0) res[1][7]=a21;
  a21=arg[2]? arg[2][9] : 0;
  a5=(a21*a5);
  a23=arg[2]? arg[2][10] : 0;
  a9=(a23*a9);
  a5=(a5+a9);
  if (res[1]!=0) res[1][8]=a5;
  a5=(a3*a10);
  a5=(a1*a5);
  a9=(a0*a8);
  a24=(a4*a9);
  a5=(a5-a24);
  a24=(a1*a8);
  a25=(a2*a24);
  a26=(a6*a10);
  a26=(a0*a26);
  a25=(a25+a26);
  a5=(a5-a25);
  a8=(a8*a5);
  a24=(a3*a24);
  a9=(a6*a9);
  a24=(a24-a9);
  a10=(a10*a24);
  a8=(a8+a10);
  if (res[1]!=0) res[1][9]=a8;
  a8=(a7*a5);
  a10=(a12*a24);
  a8=(a8+a10);
  if (res[1]!=0) res[1][10]=a8;
  a8=(a11*a5);
  a10=(a14*a24);
  a8=(a8+a10);
  if (res[1]!=0) res[1][11]=a8;
  a8=(a13*a5);
  a10=(a16*a24);
  a8=(a8+a10);
  if (res[1]!=0) res[1][12]=a8;
  a8=(a15*a5);
  a10=(a18*a24);
  a8=(a8+a10);
  if (res[1]!=0) res[1][13]=a8;
  a8=(a17*a5);
  a10=(a20*a24);
  a8=(a8+a10);
  if (res[1]!=0) res[1][14]=a8;
  a8=(a19*a5);
  a10=(a22*a24);
  a8=(a8+a10);
  if (res[1]!=0) res[1][15]=a8;
  a5=(a21*a5);
  a24=(a23*a24);
  a5=(a5+a24);
  if (res[1]!=0) res[1][16]=a5;
  a5=(a3*a12);
  a5=(a1*a5);
  a24=(a0*a7);
  a8=(a4*a24);
  a5=(a5-a8);
  a8=(a1*a7);
  a10=(a2*a8);
  a9=(a6*a12);
  a9=(a0*a9);
  a10=(a10+a9);
  a5=(a5-a10);
  a7=(a7*a5);
  a8=(a3*a8);
  a24=(a6*a24);
  a8=(a8-a24);
  a12=(a12*a8);
  a7=(a7+a12);
  if (res[1]!=0) res[1][17]=a7;
  a7=(a11*a5);
  a12=(a14*a8);
  a7=(a7+a12);
  if (res[1]!=0) res[1][18]=a7;
  a7=(a13*a5);
  a12=(a16*a8);
  a7=(a7+a12);
  if (res[1]!=0) res[1][19]=a7;
  a7=(a15*a5);
  a12=(a18*a8);
  a7=(a7+a12);
  if (res[1]!=0) res[1][20]=a7;
  a7=(a17*a5);
  a12=(a20*a8);
  a7=(a7+a12);
  if (res[1]!=0) res[1][21]=a7;
  a7=(a19*a5);
  a12=(a22*a8);
  a7=(a7+a12);
  if (res[1]!=0) res[1][22]=a7;
  a5=(a21*a5);
  a8=(a23*a8);
  a5=(a5+a8);
  if (res[1]!=0) res[1][23]=a5;
  a5=(a3*a14);
  a5=(a1*a5);
  a8=(a0*a11);
  a7=(a4*a8);
  a5=(a5-a7);
  a7=(a1*a11);
  a12=(a2*a7);
  a24=(a6*a14);
  a24=(a0*a24);
  a12=(a12+a24);
  a5=(a5-a12);
  a11=(a11*a5);
  a7=(a3*a7);
  a8=(a6*a8);
  a7=(a7-a8);
  a14=(a14*a7);
  a11=(a11+a14);
  if (res[1]!=0) res[1][24]=a11;
  a11=(a13*a5);
  a14=(a16*a7);
  a11=(a11+a14);
  if (res[1]!=0) res[1][25]=a11;
  a11=(a15*a5);
  a14=(a18*a7);
  a11=(a11+a14);
  if (res[1]!=0) res[1][26]=a11;
  a11=(a17*a5);
  a14=(a20*a7);
  a11=(a11+a14);
  if (res[1]!=0) res[1][27]=a11;
  a11=(a19*a5);
  a14=(a22*a7);
  a11=(a11+a14);
  if (res[1]!=0) res[1][28]=a11;
  a5=(a21*a5);
  a7=(a23*a7);
  a5=(a5+a7);
  if (res[1]!=0) res[1][29]=a5;
  a5=(a3*a16);
  a5=(a1*a5);
  a7=(a0*a13);
  a11=(a4*a7);
  a5=(a5-a11);
  a11=(a1*a13);
  a14=(a2*a11);
  a8=(a6*a16);
  a8=(a0*a8);
  a14=(a14+a8);
  a5=(a5-a14);
  a13=(a13*a5);
  a11=(a3*a11);
  a7=(a6*a7);
  a11=(a11-a7);
  a16=(a16*a11);
  a13=(a13+a16);
  if (res[1]!=0) res[1][30]=a13;
  a13=(a15*a5);
  a16=(a18*a11);
  a13=(a13+a16);
  if (res[1]!=0) res[1][31]=a13;
  a13=(a17*a5);
  a16=(a20*a11);
  a13=(a13+a16);
  if (res[1]!=0) res[1][32]=a13;
  a13=(a19*a5);
  a16=(a22*a11);
  a13=(a13+a16);
  if (res[1]!=0) res[1][33]=a13;
  a5=(a21*a5);
  a11=(a23*a11);
  a5=(a5+a11);
  if (res[1]!=0) res[1][34]=a5;
  a5=(a3*a18);
  a5=(a1*a5);
  a11=(a0*a15);
  a13=(a4*a11);
  a5=(a5-a13);
  a13=(a1*a15);
  a16=(a2*a13);
  a7=(a6*a18);
  a7=(a0*a7);
  a16=(a16+a7);
  a5=(a5-a16);
  a15=(a15*a5);
  a13=(a3*a13);
  a11=(a6*a11);
  a13=(a13-a11);
  a18=(a18*a13);
  a15=(a15+a18);
  if (res[1]!=0) res[1][35]=a15;
  a15=(a17*a5);
  a18=(a20*a13);
  a15=(a15+a18);
  if (res[1]!=0) res[1][36]=a15;
  a15=(a19*a5);
  a18=(a22*a13);
  a15=(a15+a18);
  if (res[1]!=0) res[1][37]=a15;
  a5=(a21*a5);
  a13=(a23*a13);
  a5=(a5+a13);
  if (res[1]!=0) res[1][38]=a5;
  a5=(a3*a20);
  a5=(a1*a5);
  a13=(a0*a17);
  a15=(a4*a13);
  a5=(a5-a15);
  a15=(a1*a17);
  a18=(a2*a15);
  a11=(a6*a20);
  a11=(a0*a11);
  a18=(a18+a11);
  a5=(a5-a18);
  a17=(a17*a5);
  a15=(a3*a15);
  a13=(a6*a13);
  a15=(a15-a13);
  a20=(a20*a15);
  a17=(a17+a20);
  if (res[1]!=0) res[1][39]=a17;
  a17=(a19*a5);
  a20=(a22*a15);
  a17=(a17+a20);
  if (res[1]!=0) res[1][40]=a17;
  a5=(a21*a5);
  a15=(a23*a15);
  a5=(a5+a15);
  if (res[1]!=0) res[1][41]=a5;
  a5=(a3*a22);
  a5=(a1*a5);
  a15=(a0*a19);
  a17=(a4*a15);
  a5=(a5-a17);
  a17=(a1*a19);
  a20=(a2*a17);
  a13=(a6*a22);
  a13=(a0*a13);
  a20=(a20+a13);
  a5=(a5-a20);
  a19=(a19*a5);
  a17=(a3*a17);
  a15=(a6*a15);
  a17=(a17-a15);
  a22=(a22*a17);
  a19=(a19+a22);
  if (res[1]!=0) res[1][42]=a19;
  a5=(a21*a5);
  a17=(a23*a17);
  a5=(a5+a17);
  if (res[1]!=0) res[1][43]=a5;
  a5=(a3*a23);
  a5=(a1*a5);
  a17=(a0*a21);
  a4=(a4*a17);
  a5=(a5-a4);
  a1=(a1*a21);
  a2=(a2*a1);
  a4=(a6*a23);
  a0=(a0*a4);
  a2=(a2+a0);
  a5=(a5-a2);
  a21=(a21*a5);
  a3=(a3*a1);
  a6=(a6*a17);
  a3=(a3-a6);
  a23=(a23*a3);
  a21=(a21+a23);
  if (res[1]!=0) res[1][44]=a21;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheelleg_nmpc_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int wheelleg_nmpc_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real wheelleg_nmpc_expl_ode_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheelleg_nmpc_expl_ode_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheelleg_nmpc_expl_ode_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheelleg_nmpc_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheelleg_nmpc_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_expl_ode_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
