/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wheelleg_nmpc_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[93] = {9, 9, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s2[23] = {9, 2, 0, 9, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[30] = {26, 1, 0, 26, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25};

/* wheelleg_nmpc_expl_vde_forw:(i0[9],i1[9x9],i2[9x2],i3[2],i4[26])->(o0[9],o1[9x9],o2[9x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  if (res[0]!=0) res[0][0]=a3;
  a1=sin(a1);
  a3=(a0*a1);
  if (res[0]!=0) res[0][1]=a3;
  a3=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][2]=a3;
  a4=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][3]=a4;
  a5=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][4]=a5;
  a6=arg[0]? arg[0][7] : 0;
  a6=(a6-a0);
  a7=2.;
  a8=arg[4]? arg[4][23] : 0;
  a9=5.0000000000000003e-02;
  a8=casadi_fmax(a8,a9);
  a8=(a7*a8);
  a10=arg[4]? arg[4][21] : 0;
  a10=casadi_fmax(a10,a9);
  a8=(a8*a10);
  a4=(a8*a4);
  a6=(a6-a4);
  a10=casadi_sq(a10);
  a6=(a6/a10);
  if (res[0]!=0) res[0][5]=a6;
  a6=arg[0]? arg[0][8] : 0;
  a6=(a6-a3);
  a3=arg[4]? arg[4][24] : 0;
  a3=casadi_fmax(a3,a9);
  a7=(a7*a3);
  a3=arg[4]? arg[4][22] : 0;
  a3=casadi_fmax(a3,a9);
  a7=(a7*a3);
  a5=(a7*a5);
  a6=(a6-a5);
  a3=casadi_sq(a3);
  a6=(a6/a3);
  if (res[0]!=0) res[0][6]=a6;
  a6=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][7]=a6;
  a6=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][8]=a6;
  a6=arg[1]? arg[1][3] : 0;
  a5=(a2*a6);
  a9=arg[1]? arg[1][2] : 0;
  a4=(a1*a9);
  a4=(a0*a4);
  a5=(a5-a4);
  if (res[1]!=0) res[1][0]=a5;
  a5=(a1*a6);
  a9=(a2*a9);
  a9=(a0*a9);
  a5=(a5+a9);
  if (res[1]!=0) res[1][1]=a5;
  a5=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][2]=a5;
  a9=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][3]=a9;
  a4=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][4]=a4;
  a11=arg[1]? arg[1][7] : 0;
  a11=(a11-a6);
  a9=(a8*a9);
  a11=(a11-a9);
  a11=(a11/a10);
  if (res[1]!=0) res[1][5]=a11;
  a11=arg[1]? arg[1][8] : 0;
  a11=(a11-a5);
  a4=(a7*a4);
  a11=(a11-a4);
  a11=(a11/a3);
  if (res[1]!=0) res[1][6]=a11;
  a11=0.;
  if (res[1]!=0) res[1][7]=a11;
  if (res[1]!=0) res[1][8]=a11;
  a4=arg[1]? arg[1][12] : 0;
  a5=(a2*a4);
  a9=arg[1]? arg[1][11] : 0;
  a6=(a1*a9);
  a6=(a0*a6);
  a5=(a5-a6);
  if (res[1]!=0) res[1][9]=a5;
  a5=(a1*a4);
  a9=(a2*a9);
  a9=(a0*a9);
  a5=(a5+a9);
  if (res[1]!=0) res[1][10]=a5;
  a5=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][11]=a5;
  a9=arg[1]? arg[1][14] : 0;
  if (res[1]!=0) res[1][12]=a9;
  a6=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][13]=a6;
  a12=arg[1]? arg[1][16] : 0;
  a12=(a12-a4);
  a9=(a8*a9);
  a12=(a12-a9);
  a12=(a12/a10);
  if (res[1]!=0) res[1][14]=a12;
  a12=arg[1]? arg[1][17] : 0;
  a12=(a12-a5);
  a6=(a7*a6);
  a12=(a12-a6);
  a12=(a12/a3);
  if (res[1]!=0) res[1][15]=a12;
  if (res[1]!=0) res[1][16]=a11;
  if (res[1]!=0) res[1][17]=a11;
  a12=arg[1]? arg[1][21] : 0;
  a6=(a2*a12);
  a5=arg[1]? arg[1][20] : 0;
  a9=(a1*a5);
  a9=(a0*a9);
  a6=(a6-a9);
  if (res[1]!=0) res[1][18]=a6;
  a6=(a1*a12);
  a5=(a2*a5);
  a5=(a0*a5);
  a6=(a6+a5);
  if (res[1]!=0) res[1][19]=a6;
  a6=arg[1]? arg[1][22] : 0;
  if (res[1]!=0) res[1][20]=a6;
  a5=arg[1]? arg[1][23] : 0;
  if (res[1]!=0) res[1][21]=a5;
  a9=arg[1]? arg[1][24] : 0;
  if (res[1]!=0) res[1][22]=a9;
  a4=arg[1]? arg[1][25] : 0;
  a4=(a4-a12);
  a5=(a8*a5);
  a4=(a4-a5);
  a4=(a4/a10);
  if (res[1]!=0) res[1][23]=a4;
  a4=arg[1]? arg[1][26] : 0;
  a4=(a4-a6);
  a9=(a7*a9);
  a4=(a4-a9);
  a4=(a4/a3);
  if (res[1]!=0) res[1][24]=a4;
  if (res[1]!=0) res[1][25]=a11;
  if (res[1]!=0) res[1][26]=a11;
  a4=arg[1]? arg[1][30] : 0;
  a9=(a2*a4);
  a6=arg[1]? arg[1][29] : 0;
  a5=(a1*a6);
  a5=(a0*a5);
  a9=(a9-a5);
  if (res[1]!=0) res[1][27]=a9;
  a9=(a1*a4);
  a6=(a2*a6);
  a6=(a0*a6);
  a9=(a9+a6);
  if (res[1]!=0) res[1][28]=a9;
  a9=arg[1]? arg[1][31] : 0;
  if (res[1]!=0) res[1][29]=a9;
  a6=arg[1]? arg[1][32] : 0;
  if (res[1]!=0) res[1][30]=a6;
  a5=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][31]=a5;
  a12=arg[1]? arg[1][34] : 0;
  a12=(a12-a4);
  a6=(a8*a6);
  a12=(a12-a6);
  a12=(a12/a10);
  if (res[1]!=0) res[1][32]=a12;
  a12=arg[1]? arg[1][35] : 0;
  a12=(a12-a9);
  a5=(a7*a5);
  a12=(a12-a5);
  a12=(a12/a3);
  if (res[1]!=0) res[1][33]=a12;
  if (res[1]!=0) res[1][34]=a11;
  if (res[1]!=0) res[1][35]=a11;
  a12=arg[1]? arg[1][39] : 0;
  a5=(a2*a12);
  a9=arg[1]? arg[1][38] : 0;
  a6=(a1*a9);
  a6=(a0*a6);
  a5=(a5-a6);
  if (res[1]!=0) res[1][36]=a5;
  a5=(a1*a12);
  a9=(a2*a9);
  a9=(a0*a9);
  a5=(a5+a9);
  if (res[1]!=0) res[1][37]=a5;
  a5=arg[1]? arg[1][40] : 0;
  if (res[1]!=0) res[1][38]=a5;
  a9=arg[1]? arg[1][41] : 0;
  if (res[1]!=0) res[1][39]=a9;
  a6=arg[1]? arg[1][42] : 0;
  if (res[1]!=0) res[1][40]=a6;
  a4=arg[1]? arg[1][43] : 0;
  a4=(a4-a12);
  a9=(a8*a9);
  a4=(a4-a9);
  a4=(a4/a10);
  if (res[1]!=0) res[1][41]=a4;
  a4=arg[1]? arg[1][44] : 0;
  a4=(a4-a5);
  a6=(a7*a6);
  a4=(a4-a6);
  a4=(a4/a3);
  if (res[1]!=0) res[1][42]=a4;
  if (res[1]!=0) res[1][43]=a11;
  if (res[1]!=0) res[1][44]=a11;
  a4=arg[1]? arg[1][48] : 0;
  a6=(a2*a4);
  a5=arg[1]? arg[1][47] : 0;
  a9=(a1*a5);
  a9=(a0*a9);
  a6=(a6-a9);
  if (res[1]!=0) res[1][45]=a6;
  a6=(a1*a4);
  a5=(a2*a5);
  a5=(a0*a5);
  a6=(a6+a5);
  if (res[1]!=0) res[1][46]=a6;
  a6=arg[1]? arg[1][49] : 0;
  if (res[1]!=0) res[1][47]=a6;
  a5=arg[1]? arg[1][50] : 0;
  if (res[1]!=0) res[1][48]=a5;
  a9=arg[1]? arg[1][51] : 0;
  if (res[1]!=0) res[1][49]=a9;
  a12=arg[1]? arg[1][52] : 0;
  a12=(a12-a4);
  a5=(a8*a5);
  a12=(a12-a5);
  a12=(a12/a10);
  if (res[1]!=0) res[1][50]=a12;
  a12=arg[1]? arg[1][53] : 0;
  a12=(a12-a6);
  a9=(a7*a9);
  a12=(a12-a9);
  a12=(a12/a3);
  if (res[1]!=0) res[1][51]=a12;
  if (res[1]!=0) res[1][52]=a11;
  if (res[1]!=0) res[1][53]=a11;
  a12=arg[1]? arg[1][57] : 0;
  a9=(a2*a12);
  a6=arg[1]? arg[1][56] : 0;
  a5=(a1*a6);
  a5=(a0*a5);
  a9=(a9-a5);
  if (res[1]!=0) res[1][54]=a9;
  a9=(a1*a12);
  a6=(a2*a6);
  a6=(a0*a6);
  a9=(a9+a6);
  if (res[1]!=0) res[1][55]=a9;
  a9=arg[1]? arg[1][58] : 0;
  if (res[1]!=0) res[1][56]=a9;
  a6=arg[1]? arg[1][59] : 0;
  if (res[1]!=0) res[1][57]=a6;
  a5=arg[1]? arg[1][60] : 0;
  if (res[1]!=0) res[1][58]=a5;
  a4=arg[1]? arg[1][61] : 0;
  a4=(a4-a12);
  a6=(a8*a6);
  a4=(a4-a6);
  a4=(a4/a10);
  if (res[1]!=0) res[1][59]=a4;
  a4=arg[1]? arg[1][62] : 0;
  a4=(a4-a9);
  a5=(a7*a5);
  a4=(a4-a5);
  a4=(a4/a3);
  if (res[1]!=0) res[1][60]=a4;
  if (res[1]!=0) res[1][61]=a11;
  if (res[1]!=0) res[1][62]=a11;
  a4=arg[1]? arg[1][66] : 0;
  a5=(a2*a4);
  a9=arg[1]? arg[1][65] : 0;
  a6=(a1*a9);
  a6=(a0*a6);
  a5=(a5-a6);
  if (res[1]!=0) res[1][63]=a5;
  a5=(a1*a4);
  a9=(a2*a9);
  a9=(a0*a9);
  a5=(a5+a9);
  if (res[1]!=0) res[1][64]=a5;
  a5=arg[1]? arg[1][67] : 0;
  if (res[1]!=0) res[1][65]=a5;
  a9=arg[1]? arg[1][68] : 0;
  if (res[1]!=0) res[1][66]=a9;
  a6=arg[1]? arg[1][69] : 0;
  if (res[1]!=0) res[1][67]=a6;
  a12=arg[1]? arg[1][70] : 0;
  a12=(a12-a4);
  a9=(a8*a9);
  a12=(a12-a9);
  a12=(a12/a10);
  if (res[1]!=0) res[1][68]=a12;
  a12=arg[1]? arg[1][71] : 0;
  a12=(a12-a5);
  a6=(a7*a6);
  a12=(a12-a6);
  a12=(a12/a3);
  if (res[1]!=0) res[1][69]=a12;
  if (res[1]!=0) res[1][70]=a11;
  if (res[1]!=0) res[1][71]=a11;
  a12=arg[1]? arg[1][75] : 0;
  a6=(a2*a12);
  a5=arg[1]? arg[1][74] : 0;
  a9=(a1*a5);
  a9=(a0*a9);
  a6=(a6-a9);
  if (res[1]!=0) res[1][72]=a6;
  a6=(a1*a12);
  a5=(a2*a5);
  a5=(a0*a5);
  a6=(a6+a5);
  if (res[1]!=0) res[1][73]=a6;
  a6=arg[1]? arg[1][76] : 0;
  if (res[1]!=0) res[1][74]=a6;
  a5=arg[1]? arg[1][77] : 0;
  if (res[1]!=0) res[1][75]=a5;
  a9=arg[1]? arg[1][78] : 0;
  if (res[1]!=0) res[1][76]=a9;
  a4=arg[1]? arg[1][79] : 0;
  a4=(a4-a12);
  a5=(a8*a5);
  a4=(a4-a5);
  a4=(a4/a10);
  if (res[1]!=0) res[1][77]=a4;
  a4=arg[1]? arg[1][80] : 0;
  a4=(a4-a6);
  a9=(a7*a9);
  a4=(a4-a9);
  a4=(a4/a3);
  if (res[1]!=0) res[1][78]=a4;
  if (res[1]!=0) res[1][79]=a11;
  if (res[1]!=0) res[1][80]=a11;
  a4=arg[2]? arg[2][3] : 0;
  a9=(a2*a4);
  a6=arg[2]? arg[2][2] : 0;
  a5=(a1*a6);
  a5=(a0*a5);
  a9=(a9-a5);
  if (res[2]!=0) res[2][0]=a9;
  a9=(a1*a4);
  a6=(a2*a6);
  a6=(a0*a6);
  a9=(a9+a6);
  if (res[2]!=0) res[2][1]=a9;
  a9=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][2]=a9;
  a6=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][3]=a6;
  a5=arg[2]? arg[2][6] : 0;
  if (res[2]!=0) res[2][4]=a5;
  a12=arg[2]? arg[2][7] : 0;
  a12=(a12-a4);
  a6=(a8*a6);
  a12=(a12-a6);
  a12=(a12/a10);
  if (res[2]!=0) res[2][5]=a12;
  a12=arg[2]? arg[2][8] : 0;
  a12=(a12-a9);
  a5=(a7*a5);
  a12=(a12-a5);
  a12=(a12/a3);
  if (res[2]!=0) res[2][6]=a12;
  a12=1.;
  if (res[2]!=0) res[2][7]=a12;
  if (res[2]!=0) res[2][8]=a11;
  a5=arg[2]? arg[2][12] : 0;
  a9=(a2*a5);
  a6=arg[2]? arg[2][11] : 0;
  a4=(a1*a6);
  a4=(a0*a4);
  a9=(a9-a4);
  if (res[2]!=0) res[2][9]=a9;
  a1=(a1*a5);
  a2=(a2*a6);
  a0=(a0*a2);
  a1=(a1+a0);
  if (res[2]!=0) res[2][10]=a1;
  a1=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][11]=a1;
  a0=arg[2]? arg[2][14] : 0;
  if (res[2]!=0) res[2][12]=a0;
  a2=arg[2]? arg[2][15] : 0;
  if (res[2]!=0) res[2][13]=a2;
  a6=arg[2]? arg[2][16] : 0;
  a6=(a6-a5);
  a8=(a8*a0);
  a6=(a6-a8);
  a6=(a6/a10);
  if (res[2]!=0) res[2][14]=a6;
  a6=arg[2]? arg[2][17] : 0;
  a6=(a6-a1);
  a7=(a7*a2);
  a6=(a6-a7);
  a6=(a6/a3);
  if (res[2]!=0) res[2][15]=a6;
  if (res[2]!=0) res[2][16]=a11;
  if (res[2]!=0) res[2][17]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void wheelleg_nmpc_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wheelleg_nmpc_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int wheelleg_nmpc_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real wheelleg_nmpc_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheelleg_nmpc_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wheelleg_nmpc_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheelleg_nmpc_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wheelleg_nmpc_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int wheelleg_nmpc_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
