red_attack_x: 200
red_attack_y: 400
blue_attack_x: 602.9
blue_attack_y: 397.9
red_supply_x: 94.0
red_supply_y: 257.0
blue_supply_x: 1126.3
blue_supply_y: 68.1
arrival_wait_time: 1.0
supply_threshold: 0.3
deviation_threshold: 0.5
hp_weight: 1.0
ammo_weight: 0.0
